# DATASOURCE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/agenda
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#FLYWAY
  flyway:
    enabled: true
    baseline-on-migrate: true